slack:
    token: "REPLACE_ME"
    retry_policy:
        trial: 3
        interval: "5s"
context_cache:
    expires_in: "3m"
    cleanup_interval: "4m"
worker:
    worker_num: 10
    supervise_interval: "10s"
